include interfaces


const
  formatsFemale = @[
    "$firstNameFemale $lastName",
    "$prefixFemale $firstNameFemale $lastName",
  ]

  formatsMale = @[
    "$firstNameMale $lastName",
    "$prefixMale $firstNameMale $lastName",
  ]

  formats = formatsFemale & formatsMale

  finglish* = @[
      "ham", "joda", "shodan", "kheili", "sakhteh", "baleh", "motmaen",
      "bashid", "hastam", "mard", "hayeh", "awli", "naboudim", "zod", "bash",
      "bego", "hameh", "daran", "mikoshan", "alaneh", "beresan", "sedayeh",
      "zarbeh", "hay", "mohkam", "dar", "khaneh", "goush", "miresad", "khodet",
      "midouni", "chi", "misheh", "vaseh", "har", "doumoun", "roshan", "are",
      "rast", "migeh", "hamineh", "douta", "rou", "hamash", "rouye",
      "badbakhta", "azmayesh", "mikonan", "mesleh", "richer", "tou",
      "dabirestaneh", "barayeh", "bazi", "kayla", "lazem", "boud", "barnameh",
      "download", "namayi", "hameyeh", "vijegi", "dastresi", "peyda", "koni",
      "eyneh", "sorakheh", "moush", "mimouneh", "feshar", "dadan", "edameh",
      "bedeh", "jasadeh", "mazbour", "bishei", "goudi", "kouhestan", "ghrar",
      "darad", "kardam", "baad", "migan", "bajehatoun", "befrestin",
      "daneshgah", "mifarmoudin", "aziz", "joun", "chera", "bayad", "kar",
      "bokonam", "porsidam", "chegouneh", "inja", "residi", "hichi", "nagoft",
      "pish", "khedmati", "lokht", "shood", "khoda", "shokr", "iran", "injouri",
      "nist", "gar", "alan", "hamamoun", "bajehayeh", "talagh", "boudim",
      "digeh", "nemisheh", "agha", "chizi", "khast", "ke", "man", "ghahraman",
      "nabard", "nahaei", "am", "shavahed", "dast", "nakhourdeh", "hamzaman",
      "arzesh", "tala", "ghaza", "khosheshan", "amad", "motmaenan", "ekhrajet",
      "mikonam", "dastat", "ghalam", "agar", "cake", "bezani", "tamam",
      "azadie", "keshvar", "hast", "baz", "tajavouz", "mishe", "hayat",
      "moshref", "moazab", "mishavam", "unjouri", "digar", "dashtam", "tam",
      "vagheiy", "zemestan", "faramoush", "mikardam", "barf", "khoushgel",
      "azizam", "behtaere", "bioftim", "zalil", "konad", "poul", "najes", "tar",
      "nadidam", "donya", "inghadr", "boland", "bashad", "hasan", "hamrah",
      "biad", "saeed", "khob", "bodam", "tamami", "mavared", "doyaye", "emrouz",
      "etefagh", "mioftad", "rouzi", "rafti", "hata", "khabat", "nadideh",
      "intouri", "seda", "mizanim", "salam", "refigh", "nakhour", "elias",
      "najounbi", "babr", "mikhouranat", "sousmar", "khatel", "kheyreh",
      "sakht", "basheh", "ageh", "gharar", "kharizeh", "aadi", "besheh", "zan",
      "shooharash", "nemishavad", "choun", "naghsh", "khoubeh", "omid",
      "behtar", "ast", "behesh", "begouim", "yek", "nafar", "parandeh",
      "gereft", "chetoure", "amadin", "hosein", "nejat", "bedin", "faghat",
      "jast", "ghiz", "bouzourg", "vali", "sabr", "konid", "noghteh", "roushan",
      "tedad", "zanani", "ghabl", "hejdah", "salegi", "ezdevaj", "kardeand",
      "chetouri", "akhe", "beranko", "khali", "timash", "board", "final",
      "delam", "nemikhahad", "beram", "doktor", "mitarsam", "dardesar",
      "shorou", "mikhan", "ghahve", "bokounandash", "babam", "dadash",
      "bargashtan", "khozestan", "miporsid", "doroost", "khaneye", "dam",
      "daghigheh", "paye", "balkoon", "nistam", "khoudet", "soal", "porsidi",
      "begou", "hasasiat", "daram", "fekr", "kounam", "hich", "kas", "andazeh",
      "khoush", "hal", "ali", "hekayateh", "rouz", "ma", "vaghti", "arabi",
      "toy", "konkour", "manfi", "zadam", "fahmidam", "arab", "natavanestan",
      "behem", "biamouzand", "vaghteshe", "gashteh", "ershad", "bejay",
      "khodrouy", "van", "tank", "bedan", "bebinim", "gondeh", "hala",
      "fekrash", "mibinam", "harfhayetan", "doroust", "belakhareh", "farghi",
      "beyneh", "jojeh", "fokouli", "faryadi", "shabih", "ghouresh", "rafteh",
      "otagh", "esfandiar", "motasefam", "aghaye", "mohammadi", "oun",
      "motaghaed", "shoma", "neshastin", "hey", "teroter", "mikhandin",
      "taghriban", "sad", "panjah", "gaz", "dourtar", "jadeh", "midounestam",
      "yeki", "medad", "kesh", "miraftam", "inke", "payan", "term", "doustanam",
      "bardashdeh", "boudam", "azadeh", "aslan", "boro", "touyeh", "haman",
      "rahat", "beshim", "taasir", "siah", "zendegi", "doo", "koudak", "tarigh",
      "gofteh", "mitavan", "bar", "besiyari", "tars", "haye", "mortabet",
      "khabar", "resani", "chireh", "haleh", "hooleh", "engilisi", "mouzakhraf",
      "zendegie", "havas", "taghir", "mikounad", "terump", "ben", "salman",
      "bishtar", "jenayat", "nefrat", "havayeh", "khoub", "barouni", "vojoudeh",
      "hes", "aramesh", "boudan", "kenar", "adam", "chahardah", "emteyaz",
      "darim", "team", "aval", "jadval", "dou", "emtiaz", "faseleh", "barah",
      "jalebeh", "chiz", "hayei", "azashoun", "mishnavim", "khodemoun",
      "mibinim", "mifahmi", "manzouram", "chieh", "agahi", "eshtebaham", "roo",
      "tekrar", "nemikonam", "tavalod", "salegit", "mobarak", "migouzarid",
      "neshan", "daham", "na", "shalvar", "kourdi", "pushidan", "soue",
      "tafahoumi", "bish", "zanouyash", "navazesh", "ahangi", "zemzemeh",
      "mikonad", "kif", "migira", "bad", "masaj", "midahad", "omidi", "kamel",
      "maghaleh", "khandam", "moured", "mofit", "sami", "riz", "khoshounat",
      "ha", "midounam", "doubareh", "mitavanam", "bebinam", "koumakash",
      "konim", "bere", "khane", "ash", "jaye", "kounjkavi", "jaygouzin",
      "davari", "koman", "ensan", "bana", "tahghighat", "khod", "bala",
      "migirad", "tavanaei", "khater", "avardan", "daghayegh", "mohem",
      "ehsasi", "pas", "gouzashte", "modat", "zamani", "komakam", "kon",
      "ghesmatam", "ghane", "basham", "betunam", "zendegim", "bedam",
      "mikhaham", "befahmam", "code", "takhfif", "estefadeh", "nemitavanam",
      "jang", "beh", "zesht", "shekl", "konam", "sar", "bardarand", "kou",
      "dash", "azad", "tamas", "baray", "mohemeh", "bastebandi", "joee",
      "bazigaram", "hengami", "soraghe", "sabzigatash", "raft", "unha", "doosh",
      "begirad", "rahash", "dahad", "khoobi", "mikony", "afarin", "natavanand",
      "konand", "mazdak", "mirzaye", "gozareshgare", "baziy", "perspolise",
      "kashima", "shod", "begam", "biya", "inga", "casi", "sohbat", "payam",
      "bedahid", "orzehy", "nadaram", "amma", "kheyli", "badjense", "boodim",
      "bale", "ettefaghan", "khoob", "aramshodan", "ovza", "tasviry", "tanha",
      "goli", "asia", "zad", "pesari", "ebraze", "alagheh", "nakardeh", "bood",
      "pishnahade", "ashnaee", "nadadeh", "nemidoonestam", "mardi",
      "namayeshgahi", "goldan", "miforookht", "donbal", "khanevadat", "oomadi",
      "rikhtet", "divist", "melyoon", "nojavan", "kharej", "mazra", "hastand",
      "raghami", "nazdik", "jameeyat", "berezil", "ketab", "manand", "simorgh",
      "morgh", "vaght", "rasideh", "sedaye", "anhaie", "bashim", "dir",
      "zamanist", "dashtane", "mahroom", "mandehand", "hamchenin", "onvan",
      "rishsefid", "modern", "daryaftam", "naghsham", "manzar", "aam",
      "karamoozi", "khafa", "morabbigari", "madarshoar", "baram", "loobiya",
      "khoord", "karde", "gojehfarangi", "rande", "shodeh", "pokhte", "dadeh",
      "moghe", "dorostkardanesh", "maryam", "panjey", "dalil", "vojood", "dare",
      "ama", "vajh", "motavajeh", "mishod", "dastbardar", "bebin", "emshab",
      "chekare", "ei", "yalla", "ghalbet", "neshoon", "salib", "bekesh",
      "khalkoubi", "ie", "ghadimha", "mikhast", "boodam", "saheb", "dokhtar",
      "mishodam", "baadesh", "hamsar", "mimord", "tak", "dokhtaram", "bozorg",
      "yadash", "kheir", "che", "royahaie", "bidar", "misham", "viraneha",
      "cheshmat", "rooz", "hame", "addi", "nafam", "tamom", "khoon", "david",
      "too", "saram", "asabaniat", "band", "naboodam", "eshtebah", "nemikoni",
      "midoonid", "hagh", "gorooh", "ketabkhooni", "dokhtaran", "noujavan",
      "darbareye", "ketabha", "tahlilhay", "ajibi", "darand", "tahlilhaie",
      "baraye", "bozorgsalan", "nadarand", "gostareye", "daghdaghehayeman",
      "ziad", "kenare", "abshar", "kone", "ghalameh", "chiiyeh", "khastegari",
      "kodoomeh", "halet", "khosh", "sedam", "nemitooni", "beshnavi",
      "daghighan", "mesle", "zanam", "marin", "maharathaie", "saz", "bargh",
      "biamoozam", "delesh", "tang", "darbarey", "mosharekat", "modiriat",
      "masael", "atefi", "baes", "sul", "dige", "moshaveram", "baste", "bashe",
      "banabarin", "sanat", "fanavar", "rahehalhay", "sari", "niaz", "mavad",
      "amade", "akharin", "roozhay", "esfand", "oon", "mivehat", "bardar",
      "tagheeri", "midadam", "damaghet", "miad", "mikhasti", "mod", "beri",
      "vahshatzade", "atraf", "negah", "oonjast", "goftam", "hasti", "anjam",
      "karhaie", "faratar", "vazifat", "khoobe", "jameeye", "pezeshki", "biyay",
      "betoonim", "pesarak", "shojaat", "marg", "kardeh", "choon", "mikard",
      "khoonash", "khaharash", "bedahad", "khandan", "shoroot", "rooye",
      "gooshiy", "motavasset", "chek", "hezar", "dolary", "50000", "verd",
      "zaboon", "tasbih", "sajadeie", "pahn", "mikonand", "faryud", "chand",
      "kharj", "kasi", "nemirehdoost", "darin", "hamishe", "zoor", "saretoon",
      "toor", "kholase", "berandcheski", "modiramel", "mara", "daneshem",
      "davat", "kard", "eraeh", "dadam", "kheradi", "kasb", "cheshmaye",
      "koochik", "baragh", "bababozorgam", "moshkel", "ghalbi", "dasht",
      "doktoresh", "goft", "saay", "narahatesh", "nakonid", "kari", "bokonid",
      "sharayet", "mikham", "oono", "bedesh", "bezar", "bahash", "shoar",
      "migim", "akhlaghay", "begoo", "age", "porroo", "mishi", "migooyam",
      "ghasd", "zehniat", "biroon", "nemiram", "mesal", "digari", "rahbaran",
      "eynak", "inha", "tashbih", "mekardam", "momkene", "hichchi", "nayad",
      "migam", "javad", "gamoonam", "chizish", "nishet", "bazeh", "behtare",
      "bahooneye", "dars", "mashgh", "khoonashoon", "malek", "chieye",
      "chandin", "zaban", "khareji", "balad", "boodand", "bedoon", "posht",
      "sahney", "barnamehay", "tond", "televisiony", "esme", "hamotaghitoon",
      "mored", "sagha", "sharmandeam", "tamaskhor", "labod", "mikhay", "jaroo",
      "khakandaz", "partam", "vay", "tarsidam", "eftekhar", "kashefhay",
      "koochooloo", "kandam", "mosallaman", "mikonim", "harfe", "digeie",
      "nadari", "tashrif", "biarin", "khouneye", "yadashti", "janeb", "shah",
      "sekeh", "mal", "sang", "bezanad", "telephonat", "oonja", "touye",
      "kelassemoun", "fazaye", "khoubi", "baham", "ouna", "tohmat", "drough",
      "gouei", "zadand", "nabayad", "mikardi", "asiaban", "chenin",
      "mostajabodave", "doa", "gandomat", "ard", "shavad", "saye", "shokouh",
      "behesht", "penhan", "shode", "vase", "pardakht", "bashgah", "moshabeh",
      "niz", "goushi", "sourat", "dorost", "asan", "momken", "salem",
      "nemitounest", "saresh", "bendazad", "payien", "khodaye", "sandough",
      "postam", "nazan", "nemibini", "dastesh", "nabashe", "sag", "nagahan",
      "nabegh", "bist", "panj", "saleei", "jalaseh", "tashakol", "dadand",
      "mesl", "baghei", "haei", "dide", "ashegh", "adami", "boudi", "naboud",
      "barat", "yad", "gozashtam", "motmaeni", "doctor", "nemikhay", "lux",
      "foroushi", "ghadam", "mizadim", "tikeh", "choub", "tabdil", "kardi",
      "ounam", "ghahramani", "mardtikeh", "jounemoun", "bikar", "bashan",
      "ketabeshoun", "khoundan", "edame", "baresi", "mokonim", "poshte",
      "pardeh", "boude", "mirim", "yeja", "estekhdam", "mishim", "komak",
      "roya", "hayash", "rouhe", "douk", "kounan", "ehsas", "dad", "tavajoh",
      "yadasht", "tashakour", "karkounan", "neveshteh", "cheghadr", "jer",
      "zani", "hamid", "nemitouni", "pishesh", "shab", "bidari", "bikhabi",
      "aziatet", "nakouneh", "nazi", "doust", "dareh", "shaba", "bekhabeh",
      "sarfeh", "vaghteh", "onja", "noe", "jadidi", "rish", "sefid", "hul",
      "padidar", "mohit", "bashand", "mikhahad", "faza", "avaz", "aghaeideh",
      "mazhabi", "nadashte", "hol", "dadi", "mikhad", "zaman", "aghab",
      "bargardeh", "zahere", "mahsoul", "chetourie", "hamisheh", "filma",
      "mididam", "migouftan", "nadaran", "mikounam", "intour", "nazaram",
      "mojasame", "maragheb", "younan", "bastan", "sakhtan", "khiaboun", "dari",
      "rah", "miri", "nafari", "kenaret", "rad", "mishan", "darmored", "dolar",
      "harf", "mizanan", "ozr", "shekam", "milouland", "sorat", "jarou",
      "khakendaz", "barayash", "miavarand", "khanouma", "miomadan", "maghazeh",
      "migoftan", "lebas", "palangi", "ranghaye", "halam", "hava", "zoud",
      "tarik", "ghoutbe", "jounoub", "bemirir", "ghabret", "miofteh",
      "hadaghal", "shesh", "mah", "mousri", "atrafe", "mobtala", "mishavim",
      "emsal", "lig", "torkeyeh", "ghodrat", "maharatam", "dastash", "avardam",
      "bank", "vam", "begiran", "khodrosaz", "naghdi", "aghsat", "zuck",
      "udameh", "khobieh", "rouznameh", "gouftan", "radio", "motaasefamaf",
      "morede", "joloush", "tamos", "telephonie", "rashid", "pour", "kode",
      "melish", "froush", "gozashte", "sham", "bache", "bakhtim", "shoudin",
      "anjoiman", "meli", "jahan", "gardan", "ozviat", "batel", "mikoune",
      "vazir", "unja", "negaran", "nabashid", "hayie", "rokh", "jahat", "salah",
      "shomast", "shayad", "kesel", "konandeh", "nazar", "doukhtareh",
      "mizadam", "bro", "daavatash", "tejarat", "khobist", "milion", "mardom",
      "hamin", "mikeshe", "paein", "ina", "shouneh", "asef", "toul", "noh",
      "sal", "recorde", "behtarin", "amal", "doran", "residand", "zendeh",
      "atash", "besouzid", "neshastegimam", "vaghean", "haghighat", "khoulase",
      "khobeh", "farsh", "nandakhtim", "ashpaz", "residim", "hodoude", "saat",
      "baghi", "mondeh", "mitavanim", "peyman", "shavim", "mohite", "biroun",
      "pasho", "jayeh", "bezan", "neveshte", "yebar", "bekhan", "phibi",
      "tastial", "kam", "adat", "khoudam", "umadam", "didam", "moh", "madar",
      "shoudand", "khoudeshan", "hanouz", "boudand", "ashena", "miresid",
      "ghatan", "tasmim", "toust", "tavajo", "tasir", "migouzarad", "meghdari",
      "tamarkoz", "poor", "energyie", "mosbat", "hali", "khounam", "joush",
      "amadeh", "eeteraz", "aparteman", "khabari", "nashod", "ajibeh", "fough",
      "takhasoseshoun", "namak", "nashnasie", "zang", "ojagh", "jor", "haie",
      "asheghet", "shodam", "sandalim", "frou", "raftam", "sabraneh",
      "mountazer", "yekam", "radif", "ertebate", "mon", "beham", "zadim",
      "hourouf", "figilish", "neveshtan", "tayp", "nemikounid", "vezarateh",
      "kharejeh", "amrica", "eghdam", "moughabele", "campain", "vared", "nasho",
      "arshad", "khodeshoun", "daryaft", "kardan", "sobh", "cheshmam",
      "shodanam", "lezat", "mibaram", "daftare", "vakili", "neshasteh", "tarin",
      "saregh", "herfe", "ashna", "shodam1", "khuneh", "miz", "avalin", "bari",
      "farghe", "pessar", "bacheh", "dokhtare", "hamsayeh", "davam", "begirin",
      "bebinin", "chetori", "pesar", "hash", "mizaneh", "komakesh", "konin",
      "dastani", "darbureye", "eshgh", "begouyam", "shokrat", "baba", "alaki",
      "sholoughesh", "mikonid", "nadouni", "kardim", "motakhaseh", "nabeghe",
      "mikhastam", "mageh", "gofte", "panir", "khahi", "pazirofteh", "labkhand",
      "mizad", "berin", "piri", "meayad", "raftim", "biron", "khiyaboun",
      "jashn", "mord", "noghat", "niloufar", "geryan", "kheily", "khoube",
      "khab", "daghighe", "baghal", "vel", "bekhabid", "besabeghei", "samt",
      "javanan", "sarazir", "mishavad", "bastegi", "DQ", "mekham", "daavatet",
      "peasar", "stadium", "footbal", "moghee", "hamle", "mogheeat",
      "khatarnak", "teameshoon", "baazi", "afrad", "aan", "rok", "goei",
      "radikal", "minamand", "jaei", "shakhsan", "ahameiat", "midahid", "amaa",
      "mostaghim", "chalesh", "mikeshid", "vey", "ghorbani", "nakardand",
      "midanam", "kaar", "micard", "kheyr", "khosounat", "beshnasim",
      "anjameshan", "nadehim", "behet", "dadim", "por", "zarbe", "mohkami",
      "mizanand", "nime", "khahar", "mohsen", "telephoni", "ashana", "rabeteh",
      "alaghe", "khbar", "dastan", "migardad", "chnda", "tahamol", "nadram",
      "sabet", "raeis", "khneh", "kist", "digary", "bebina", "tourisr",
      "azarbaijan", "nadide", "haraji", "kharidamesh", "shila", "sedayat",
      "joury", "nemikhahim", "in", "beboosam", "shady", "nadozdideim", "vary",
      "miravad", "rasteoon", "chap", "zahremar", "mikhndi", "azat",
      "nemitarsam", "manam", "mamnoon", "davar", "hodood", "faght", "ezafeh",
      "jaleb", "hayeshan", "chesm", "azashoon", "nemidashtand", "roozi",
      "doreshan", "faravan", "miguyad", "jayeshan", "miayad", "hameshan",
      "mibarad", "montazer", "baademan", "spania", "porteghal", "hastim",
      "sooud", "sherkat", "yabi", "siasat", "sath", "jahani", "tahir",
      "shekayat", "erae", "midahand", "besiari", "vard", "bazar", "mishavand",
      "bedoun", "tazeen", "tarh", "zarifi", "dashtand", "hotel", "kouchak",
      "boudeh", "las", "gas", "ravim", "rabetamoun", "mordeh", "aast",
      "amalkard", "behtary", "khahid", "garm", "shayesteh", "misahvid", "va",
      "eghragh", "oonaei", "migouyand", "pool", "cheshm", "koor", "rajeb",
      "hormon", "nemidanand", "mian", "khatere", "raftanesh", "shahr",
      "bezanid", "baese", "narahati", "ye", "tor", "mikoni", "cafein",
      "mikhoram", "niaat", "bokon", "javani", "begoueim", "ghegounei",
      "mitavand", "vigheh", "mogheiat", "amrg", "vazendegi", "inam", "chart",
      "jalase", "jomee", "adabi", "krkhneh", "asar", "paeein", "istgah",
      "otobus", "nemishenasi", "dastet", "dard", "nakonad", "arros", "golam",
      "horouf", "fingilish", "type", "nemikonid", "aya", "ahmagh", "jigh",
      "agah", "sakhtim", "nagerfte", "gosha", "ghazaha", "fayede", "toulani",
      "rosva", "nistand", "chetor", "tonesti", "begouei", "slam", "dokhtary",
      "jonoubam", "khouzestan", "chon", "andaze", "gholdori", "azar", "taraf",
      "digaran", "roubrou", "dom", "khorous", "ghasam", "hazrat", "abaas", "ra",
      "ghablesh", "rabet", "zade", "barname", "rizi", "and", "moragheb",
      "mehmanan", "khnde", "baran", "eftezah", "motovajeh", "shodim", "afradi",
      "biadabi", "tajrobe", "vazife", "sholugh", "shmare", "do", "bai",
      "beshin", "joon", "karrim", "dashti", "javan", "nemigam", "dahanam",
      "ghors", "mahz", "etelaa", "dafe", "beayad", "goushiash", "azash",
      "begirim", "nayamade", "tir", "neshoun", "mizane", "gol", "arousi",
      "sheh", "raychel", "dabirestan", "kash", "beshe", "khas", "joei",
      "mikhary", "ghorban", "dastetan", "khodesh", "bebinid", "asemoun",
      "mididi", "alame", "balon", "arezoo", "zamin", "fasele", "gerfte",
      "harekat", "mikardand", "rahabaran", "charsad", "morde", "noght",
      "etesal", "nabashad", "hat", "khouban", "bavar", "nisti", "chirismas",
      "escelet", "fel", "enfeal", "mizan", "eshtebahi", "darou", "bimar",
      "shenide", "ghareman", "amanam", "kale", "bokonim", "ghif", "hosini",
      "midooni", "amnzouram", "chie", "gozasht", "estefade", "taze", "tanh",
      "kase", "ebraz", "nashode", "pache", "tafavot", "ziadi", "nahve", "eydeh",
      "eijad", "namiri", "parvane", "khord", "hayajan", "angiz", "bargashtim",
      "hodoud", "khashmnak", "omadin", "dehid", "toulesh", "dadid", "mahsa",
      "kharchang", "pezeshk", "elat", "unisrf", "hamkaran", "khat", "andazi",
      "ebtekar", "majbour", "naboudam", "akhiran", "moze", "sakhtgiranei",
      "alayhe", "zendan", "khosusi", "ghomash", "divar", "sourakh", "ijad",
      "kardand", "hangam", "sakhti", "beresand", "ghahti", "begzarad", "teflak",
      "bozorgam", "shohar", "gofti", "bemirad", "gerye", "khodaya", "pedar",
      "sharmande", "bara", "moredat", "karadm", "ramezan", "eyd", "fetr",
      "halt", "khobi", "ester", "bebakhshim", "yekishan", "khodam", "mark",
      "yaghe", "nimishe", "bishe", "ney", "kezaran", "mehman", "bekesham",
      "moshraef", "jori", "halouvin", "maghnae", "sabz", "chador", "batoom",
      "shoke", "sigar", "bekeshi", "mamnoo", "key", "tamoom", "keylihatoon",
      "shekast", "kardeid", "amdeidinja", "aram", "shavid", "kharab",
      "aaghelne", "walkman", "bede", "enghadr", "nejabat", "sherafatesh",
      "rastesh", "sali", "sabeghe", "zood", "aayam", "emtehant", "bekhounam",
      "jaelb", "injast", "mikhondam", "jazab", "khordad", "ghazie", "chnd",
      "begid", "khastid", "sfandiar", "fahmide", "khodash", "ghahramanan",
      "ghatl", "eyek", "estghlai", "yaft", "paeiz", "shdand", "khdeshan",
      "mashin", "vaghei", "begir", "hfte", "gereftam", "falj", "besham",
      "majid", "shekaf", "rafte", "afrigha", "resiadan", "khanoum", "nemizanad",
      "mamlov", "giahan", "heyvanat", "mibashad", "kelaseman", "gholei",
      "maharat", "tool", "avarde", "pesaram", "masiha", "rang", "mokhtalef",
      "mibinid", "gooletoon", "beezanadman", "babash", "mikoshdamash",
      "mohavezat", "kee", "ferestade", "migiram", "loghat", "miavordam",
      "sahebam", "ghalade", "barayam", "joor", "asheghe", "chips", "khande",
      "koneshgar", "aali", "azatoun", "delkhoram", "moones", "oghat", "khoshi",
      "dastte", "oomadim", "khoonam", "joosh", "amdae", "eteraz", "molaheze",
      "migid", "hamlshode", "zarf", "moosh", "mibord", "kashef", "sarzamin",
      "door", "oftade", "jadid", "rabete", "bargharar", "lahze", "gooshi",
      "farar", "orze", "biroonan", "daroonan", "bashar", "hamele", "tabl",
      "shahed", "etare", "donbale", "kashki", "mirafti", "gerefte", "khatab",
      "mibini", "daste", "golie", "khodat", "aab", "bia", "jamaash", "vaay",
      "merci", "berim", "bokhorim", "spani", "porteghl", "marakesh", "dolat",
      "aamad", "sale", "mahal", "varedat", "khodro", "mitavanest", "khanei",
      "bozorgi", "moderni", "neissan", "biavarad", "biaiam", "ja", "vagth",
      "khordan", "satri", "rofagha", "jeloyam", "sabza", "takht", "neshast",
      "haghi", "nemidehad", "goone", "pishnahad", "shoghli", "tashvigh",
      "bepazirand", "forsat", "avarand", "sevom", "vagheei", "paradaim",
      "tosee", "gereftan", "saree", "konkoor", "araab", "natavaneste",
      "biamoozand", "ravand", "gera", "jaa", "khaheshan", "hayatetan", "bare",
      "massael", "aatefi", "albate", "begooyam", "taamodi", "saaei",
      "negaheman", "tehran", "chesh", "entezar", "nbashid", "elhi", "tan",
      "rasta", "tosie", "moshaverati", "mitavanid", "naam", "tahvil", "dahid",
      "jan", "nailon", "meshki", "koochak", "tahdid", "leh", "emrooz", "darid",
      "roozegar", "ghadim", "padeshahi", "jadei", "tebgh", "ghanoon", "beravim",
      "tahghighi", "faregh", "tahsilan", "madares", "ferestadim", "sazman",
      "migoftand", "barkhi", "eyde", "yam", "mahdood", "amaad", "chndler",
      "melli", "pooshan", "valibal", "chehel", "bartar", "etefaghi", "oftad",
      "aavardam", "haam", "nemizanand", "tavousi", "daasht", "par", "mikand",
      "mirikht", "vasvase", "bargardam", "kaado", "tavalodat", "barayat",
      "avalan", "mrc", "deght", "hamegi", "saniaan", "manzoor", "chahar",
      "nesbat", "tolid", "karkonan", "saham", "teye", "dore", "bazaar", "jelo",
      "nemoone", "tasaadofi", "bihoosh", "ghadr", "bihosele", "khaste", "aksar",
      "farzandan", "abdolaah", "maraasem", "aroosi", "tassiir", "migozarad",
      "maghz", "iraniol", "aasl", "tavanest", "parleman", "felorida", "ejaze",
      "biayad", "beravad", "bam", "khaneshan", "miavard", "masool", "livan",
      "vahid", "eynaak", "kiee", "dozdi", "nisteshare", "bemostraah",
      "aanhjast", "aavardid", "taghsir", "madyoon", "trump", "bensalman",
      "jenaayat", "daarad", "saayeman", "makhsoosan", "ayande", "yesan",
      "aashnaa", "aksi", "montasher", "ghablash", "slide", "misazam",
      "gozareshi", "khataa", "amniati", "bayan", "mokard", "mozooat", "henry",
      "dovomi", "room", "aroom", "peer", "shodid", "mishid", "naghashi",
      "ghablan", "gomesh", "kardei", "han", "taajobi", "nadarad", "tasmimaat",
      "khodavand", "ghdrat", "dark", "maa", "khrej", "sood", "namayesh",
      "hafte", "hang", "hafa", "yeho", "goftman", "nemikhaham", "alaan",
      "javabam", "beravid", "natije", "residid", "begooid", "havaa", "tagheer",
      "nagoftam", "maman", "migzaroonim", "bezaresh", "bedanam", "kot",
      "napooshidam", "sakhtesh", "baadi", "payani", "khahad", "moraghebeshan",
      "bashi", "jaaye", "joori", "pesaresh", "mizanad", "kooh", "navard",
      "mashrooh", "yecapitan", "valleyball", "banovaan", "ghrize", "shoharash",
      "ayanei", "motohavel", "mokhareb", "pishbini", "tafakor", "janbe",
      "dashte", "beravam", "bardaram", "sandalimam", "froo", "sabrane", "betor",
      "hazer", "saal", "tahaghogh", "amali", "paydar", "khata", "rasm", "ghol",
      "hayeman", "nemikonim", "toam", "sht", "e", "agh", "sobhi", "doaei",
      "midehi", "behemaan", "navar", "khreghol", "ade", "pire", "bimaar",
      "zende", "namanad", "gonde", "hastesh", "bangeladesh", "hamkarani", "dah",
      "javaan", "zamie", "faani", "amouzesh", "betavanand", "mecanic", "motor",
      "khdamat", "telephon", "hamraah", "shavand", "amee", "khoadam", "sharab",
      "sib", "khordim", "omran", "berry", "bebinand", "cafe", "holz", "food",
      "bezanand", "vagheaan", "nakhor", "dooste", "dokonat", "hezaro", "modir",
      "aamel", "soup", "cample", "tazegi", "nesf", "reside", "shanzdah",
      "nemidi", "hanooz", "short", "mipooshan", "khelal", "kaaghaz", "sargarm",
      "dardetan", "nemikhorad", "fateme", "salehi", "sre", "paark", "saei",
      "sakhre", "navardi", "morabi", "boodje", "app", "tarahi", "jameeshan",
      "begiramash", "bas", "ziba", "neshani", "ghoran", "migozarand",
      "mikonanad", "nashokri", "begirid", "benevisid", "gonjeshki", "ajale",
      "tavan", "ataash", "barmigasht", "ghorooreman", "kol", "keyhaan",
      "yegane", "hooshmand", "midanim", "kodaam", "jabe", "maal", "jash",
      "doostam", "niazmandim", "mitoni", "bechini", "mojezei", "nabood",
      "mishnavam", "migooei", "mitavani", "safar", "sarzamini", "gom", "lotfan",
      "yadat", "migoftam", "beravi", "mimiram", "manzooram", "ehtiaji",
      "miayam", "edei", "khahand", "ravesh", "fahesh", "maghamat", "amricaei",
      "tose", "ebteda", "nezamian", "khalij", "fars", "sepas", "ezhar", "mikha",
      "peigiri", "jaha", "oou", "motokhases", "zaheran", "mibayesti", "nazaei",
      "zira", "alaf", "saghe", "khezaran", "atraaf", "shekaste", "mavaared",
      "anaam", "koja", "abar", "dashtim", "takhte", "gerooni", "filter",
      "nakesham", "fekram", "apartemaan", "khaane", "bokonandesh", "maani",
      "beshinad", "doostanash", "gap", "aroos", "bigaari", "tamaam",
      "barashgardaan", "ndorosti", "amniat", "khaab", "rafteim", "rahati",
      "click", "aaghaz", "emaal", "feshaar", "minaamim", "ramzi", "mizanam",
      "rasti", "kafsh", "hyam", "yat", "nakhoshayand", "baashad", "mitavaani",
      "tanhaa", "basi", "mrgam", "mage", "raazi", "takhasos", "etelaat",
      "ghalat", "makaani", "rokhdad", "chekasi", "zadid", "balke", "vageaan",
      "tarsnaak", "fard", "momtazi", "hastid", "shomaa", "raahat",
      "peymaanaaan", "hemaayat", "emkan", "nadaarad", "magar", "aghl",
      "mentefg", "nemiaayad", "mikhaaham", "soushi", "bokhoram", "tori",
      "havaas", "raa", "part", "taa", "kermanshaah", "bardaarad", "cheraa",
      "istaadi", "doost", "daashtan", "inaa", "baa", "bandi", "daashtand",
      "shookhi", "jeloy", "dovom", "aanjaa", "shaahedi", "hozoor", "edaame",
      "besyar", "zaroori", "khaahad", "begzaar", "delkhosh", "baasham",
      "maadar", "hasht", "baraaye", "mesaal", "eraa", "daashtam", "khial",
      "khodaa", "biaamorz", "baghalash", "maamaan", "baabaa", "biaayand",
      "kaashef", "fogholaade", "sarzaminhaay", "oftaade", "haa", "naboodash",
      "dor", "otaagh", "donbaalash", "soraagh", "maadaraan", "shahrestani",
      "biaaeid", "bezanim", "fibi", "barnaame", "daaram", "aadat", "fazaa",
      "aamadam", "maah", "daaneshgaah", "aare", "daashtim", "motaghedand",
      "kamtar", "rahbaraan", "miresand", "samaanvand", "porose", "mamoolan",
      "toolaani", "farib", "dade", "baavar", "edi", "migi", "vaasat", "ajibe",
      "baar", "gofteam", "nemidoonam", "aabshaar", "film", "doorbin", "makhfi",
      "shaan", "didim", "vaaghean", "amlaaki", "vasse", "maadaram", "otaaghesh",
      "2013", "ejraaei", "moasese", "mohandesi", "beynolmelali",
      "saanferaansisko", "mikhaad", "toram", "moaalej", "vaziat", "bimaari",
      "minaa", "baraadar", "saale", "tozih", "daad", "nemikardam", "nasl",
      "azimi", "javaanaan", "shorof", "ers", "bordan", "donyaa", "mikhaahad",
      "nemidaanam", "esraari", "kachal", "etelaaaat", "ghadri", "ahamiat",
      "kaa", "movazaf", "darsad", "zamaan", "ide", "enteshar", "ekhtesas",
      "dehad", "25", "salaam", "mikonin", "goroohi", "migirand", "haml",
      "naghl", "maloolaan", "jame", "maahiat", "haalat", "zediat", "daari",
      "injaa", "noghte", "mikhaabam", "koli", "zahmat", "saa", "bidaar",
      "asabaani", "nojavaan", "yaa", "jaaei", "khoshoonat", "agarche",
      "kaarkonaan", "adab", "movafaghiateshaan", "kharaab", "vasile",
      "sargarmi", "rafigham", "mosesh", "aavard", "jedi", "kaaleske",
      "mikhaahi", "beraghsam", "parvaaz", "kaamelan", "motafaavet", "sandogh",
      "baazneshastegi", "moalemaan", "shikago", "sarmaaye", "gozaar", "aagaah",
      "meliaard", "dolaari", "daastaanash", "mofasal", "jaaleb", "dokhtari",
      "jonoobam", "khoozestaan", "jelooyash", "moghaavemat", "said", "soaal",
      "gamoon", "nakonam", "daashte", "migoft", "talaa", "miforokhtam",
      "midaadam", "behetoon", "afsoos", "mikhord", "nemitoone", "komakemoon",
      "darham", "barham", "maloom", "amn", "maand", "monjar", "kaylo",
      "aalmaan", "nemikhaam", "maashin", "gozaashte", "aamadeand", "kaapootash",
      "dozdideand", "sarmsaam", "aavari", "tarif", "yani", "ghabool", "haalaa",
      "taaadol", "paaydaar", "ziraa", "jamaavari", "shakhsi", "aanhaa", "sathi",
      "ghaabel", "tasavor", "movaafeghat", "kardeim", "moonika", "jahaani",
      "saalmandan", "taktak", "haaye", "iraan", "tabrik", "moghei", "dandaan",
      "haayam", "mesvaak", "bemaani", "nemitavaanam", "mehr",
      "baazneshastegaan", "ajab", "roopoosh", "mipooshi", "del", "nagir",
      "khaanom", "aban", "bordam", "daadam", "firizer", "nadaaram",
      "gharaaremoon", "goldaani", "bishtari", "borde", "hamaan", "goldaan",
      "saade", "migiri", "aah", "khodetaan", "chekaream", "raast", "baavaram",
      "parande", "nadidan", "saaghe", "kheyzaraan", "jasad", "khooni",
      "nemikhaad", "belit", "estefaade", "cheshmhayam", "nemikhaaham",
      "gozaaresh", "aljazire", "ghatar", "elaam", "ebtedaye", "zhaanvie",
      "opek", "khaarej", "negaraan", "nabaashid", "haayi", "midehad", "salaah",
      "shomaast", "antern", "nafahmidam", "haminghadr", "naresidam", "begiram",
      "bacheam", "300", "melioon", "dolaar", "kaaseb", "baaes", "eftekhaar",
      "movafagh", "koori", "doshmanaan", "kharidam", "khoobesham", "badesh",
      "bordamesh", "panaahgaah", "zare", "ghatre", "misoozam", "mimaanam",
      "khoone", "parvaane", "jaan", "baaz", "kheyret", "bedehad", "mooye",
      "maadarash", "javaanish", "aatash", "paarei", "boode", "zajr", "nashavad",
      "miravam", "miresam", "shenidid", "migooyand", "aamadim", "savaab",
      "kabaab", "hekaayat", "mamaan", "polis", "mifahmad", "barkhord",
      "moghaser", "ketaab", "kharidan", "lebaas", "masihaa", "beistid", "goosh",
      "goftand", "hajm", "moghaayese", "aabi", "miaavari", "besyaar", "ziaad",
      "fayedei", "midaani", "viner", "paasokh", "mideham", "aanche", "miaamad",
      "aaheste", "raah", "naro", "baraayash", "sibil", "keshidam", "paarti",
      "deleshaan", "bizaarid", "tamizeshaan", "nakarde", "gozaashtam", "jaam",
      "postchim", "laazem", "meghdaar", "khashmgin", "farzandaan", "moshtari",
      "aapshen", "daarand", "nerkh", "bahre", "baank", "khodrosaaz", "paaintar",
      "eyn", "sooraakh", "mimaanad", "sedaa", "vakman", "tooye", "nemishavam",
      "donbaal", "pishrafte", "hedie", "daaneshgaham", "digarash", "gozaari",
      "nahaad", "behdashti", "afzaayesh", "dahim", "say", "bikhialash",
      "beshavi", "mahram", "zendegiam", "mahsaa", "beshavad", "aaghelaane",
      "khoshkam", "ashk", "shor", "rikhtand", "saaf", "zolaalash", "hasoodiam",
      "moche", "paayam", "aasib", "naansi", "taamson", "ekhraaj", "raahi",
      "aahaay", "daarid", "garme", "kaash", "bokhaari", "khaamoosh", "monim",
      "naft", "baahaal", "asabi", "injaayam", "baayad", "hadeaghal", "biayi",
      "kenaar", "goor", "baaghebaan", "biavaram", "hayaat", "beresad",
      "khodaaye", "negaah", "morabihaa", "mitavaanand", "bokonand", "nemiravam",
      "modire", "bozorgtarin", "kheyrie", "shahrash", "bejaaye", "berid",
      "baraayam", "ghazaa", "biavarid", "dahanetaan", "bebandid", "dood",
      "nokte", "haminjaa", "badan", "sharaayet", "bekhaahi", "javaabash",
      "bedehi", "nemidaanim", "sedaai", "shenidam", "haal", "hosele", "paa",
      "beshavam", "baazaar", "bioftam", "biayam", "aakhe", "sigaar", "aaraam",
      "maahi", "ghermez", "paarche", "miavaram", "ahsaasaat", "angize",
      "migozaarad", "hamintor", "raftaar", "digaraan", "motaaleaati", "tanzim",
      "jaayi", "konande", "shaahed", "gostaakhaane", "aazmaayeshgar",
      "tahghigh", "mishodand", "aasef", "ghadeshaan", "mikhaahid", "baashid",
      "saadeei", "bedaanid", "nadaanid", "javaab", "raftaaretaan",
      "nayandaakhtam", "nakardam", "tanbalam", "nakhaahid", "boodi", "nazanim",
      "jozaam", "mazerat", "shoroo", "mohtaram", "farmaa", "naachaaran",
      "midonid", "hodoodi", "midaanam", "aks", "delash", "haayash", "ghaaedi",
      "shanbe", "madrese", "perspolis", "mibinad", "hamkaarat", "eshaare",
      "mostaraam", "yaadam", "narafte", "motaasefaane", "koodak", "mafaahim",
      "aazaarande", "naaraahat", "migooyad", "doostash", "nemitavaanad",
      "resideand", "aazar", "hatman", "faraamoosh", "baam", "faraar",
      "jelotaan", "gereftand", "farmoosh", "naakhonat", "aakhar", "hesaabiand",
      "daaryoosh", "shirinkaam", "lenge", "shekaayati", "kaashima", "entegham",
      "baakht", "saaypa", "hazfi", "porsid", "aayaa", "behboodi", "khaahart",
      "haazeri", "ehda", "hodoodan", "khashmnaak", "tim", "negahdaar",
      "daadand", "maan", "nemigooyam", "etelaaet", "khaast", "gooshish",
      "aamade", "nayaamade", "neshaan", "jamat", "martike", "nim", "kiloo",
      "chaagh", "shodi", "mitarsim", "hamdeli", "shan", "polo", "yaad",
      "tamrin", "digaretaan", "moshkelemaan", "nemitavaanand", "begooyand",
      "mazloom", "defaaand", "halaal", "shir", "nemigozari", "sedaayi", "esm",
      "kaamelash", "gofi", "navaar", "azataan", "nemikhaahi", "asabaaniash",
      "sard", "baash", "ziaadi", "yaadat", "khoshgel", "aavardi", "havaaye",
      "baarooni", "aaraamesh", "boodan", "aadam", "khoshhaal", "zogh",
      "tashakor", "mibarim", "noche", "vafaaye", "negaraanet", "shokolaat",
      "khoshash", "miaayad", "biaa", "royaa", "kaari", "daashti", "anjaam",
      "midehand", "movaghatan", "nayaamadeam", "100", "deltang", "didanash",
      "baashi", "bebinish", "daashtanash", "bahs", "hataa", "doostat",
      "saahebam", "ghalaade", "shirini", "pishash", "mohemtar", "kashf", "raaz",
      "moamaaye", "ghadimi", "hamkaari", "taraahi", "olgoo", "roozaane",
      "afraad", "abzaari", "zaif", "zamine", "daadan", "maghta", "dabestaan",
      "havaasat", "avazi", "raas", "giaahaan", "heyvaanaati", "mibaashad",
      "sagetoon", "mast", "aanjayash", "dobaare", "nafas", "migiradva",
      "khoshat", "bekhaani", "biaayi", "kelaas", "khaaneat", "abaasi", "ehsaas",
      "didanet", "khoshbakhtam", "taaze", "ghesmat", "besiaari",
      "mitavaanestim", "haftaad", "pele", "soood", "knim", "revaayat",
      "hamdigarand", "pir", "mishavid", "aashghaali", "midaanad", "mojoodaati",
      "zhaaponi", "akhlaagh", "baakhtand", "natavaanestand", "varzeshgah",
      "tamiz", "raabete", "ezdevaaj", "azashaan", "khodemaan", "iraani",
      "savaar", "keshti", "moraagheb", "ghaayegh", "tashrifaat", "shoharjaan",
      "khoshbakhti", "mahaale", "ferestaade", "afzood", "hamaanand", "saayer",
      "gheyr", "ozv", "taahodaat", "saazmaan", "paayband", "hezaar", "chaahaar",
      "koodaki", "make", "goshood", "edeaaye", "peresident", "kenedi",
      "eghdaam", "teror", "paap", "tavasot", "siaa", "koodakaan", "aamrikaaye",
      "jonoobi", "servatmandaan", "aamrikaai", "azaaye", "badaneshaan",
      "shodeand", "CIA", "shaayad", "nabaashad", "raadikal", "niaazmandim",
      "fardaa", "setaareye", "kamrang", "lebaasash", "nemikonad", "nagaraan",
      "haapoo", "saandevich", "bokhor", "amene", "omidvaar", "shekaaf",
      "ertebaat", "saaleye", "ijaad", "aashegh", "aasheg", "sarkaar",
      "khodaayam", "baahaat", "biaayam", "rais", "bande", "biaaid",
      "sokhangooie", "ghaayem", "montazeram", "biaayad", "bekhaabim",
      "movaazebami", "betavaani", "sor", "bokhori", "nakardani", "ordibehesht",
      "emsaal", "jazaab", "afsorde", "baghaayaaye", "janin", "maande",
      "mipoosham", "gorbe", "migooim", "motaale", "kardeam", "masoolin",
      "zhaapon", "nazadan", "ozrkhaahi", "ritmash", "sahaam", "tamaashaa",
      "rooze", "tarz", "vahshatnaaki", "shaad", "zehnam", "resid", "haani",
      "khoshgele", "naazash", "mitavaanam", "kheyrat", "mardood", "naa",
      "midid", "velash", "shaam", "mersi", "kaareshaan", "chist", "baghie",
      "rahaa", "jami", "saazande", "taghiraat", "behbood", "maali",
      "nemikhaahand", "mazraeye", "manaategh", "roostaayi", "baashand",
      "mosaaferam", "gharaar", "afsaraan", "1975", "estekhdaam", "velaadimir",
      "pootin", "reshte", "tooit", "emperaatoori", "rasaanei", "tasis",
      "khaahim", "pardaakht", "ghazaai", "mikoshad", "maghaamaat", "nezaamiaan",
      "faars", "ezhaar", "bepardaazand", "kami", "andaazeam", "mikhari",
      "chehre", "gharib", "asaatid", "paaye", "shenler", "nemifahme",
      "paadeshah", "faraa", "khaand", "aknoon", "monzoor", "migofti", "masale", "hormati"
    ]

  firstNamesFemale = @[
    "فاطمه",
    "زهرا",
    "مريم",
    "معصومه",
    "زينب",
    "مرضيه",
    "صديقه",
    "زهره",
    "ليلا",
    "طاهره",
    "اعظم",
    "سميه",
    "سكينه",
    "رقيه",
    "ريحانه",
    "نرگس",
    "خديجه",
    "مهديه",
    "الهام",
    "اكرم",
    "محدثه",
    "راضيه",
    "بتول",
    "طيبه",
    "محبوبه",
    "فائزه",
    "عصمت",
    "الهه",
    "كبري",
    "سارا",
    "فرزانه",
    "نجمه",
    "مبينا",
    "عاطفه",
    "سمانه",
    "مليحه",
    "صغري",
    "مائده",
    "مينا",
    "مهسا",
    "مهناز",
    "هانيه",
    "حميده",
    "فرشته",
    "ناهيد",
    "فهيمه",
    "نسرين",
    "سميرا",
    "اشرف",
    "كوثر",
    "فريبا",
    "فاطمه زهرا",
    "فاطمه سادات",
    "مهري",
    "افسانه",
    "ربابه",
    "نازنين زهرا",
    "سحر",
    "اميد",
    "مهين",
    "آمنه",
    "منصوره",
    "حديث",
    "نرجس",
    "مطهره",
    "ندا",
    "مژگان",
    "پروين",
    "فريده",
    "پريسا",
    "شهناز",
    "آرزو",
    "شهربانو",
    "رضوان",
    "نفيسه",
    "عفت",
    "ستايش",
    "زهراسادات",
    "حديثه",
    "سيده فاطمه",
    "اقدس",
    "مليكا",
    "عارفه",
    "نگار",
    "اسماء",
    "پروانه",
    "ثريا",
    "حكيمه",
    "حنانه",
    "فاطمه السادات",
    "هستي",
    "آسيه",
    "آزاده",
    "زهراء",
    "سيده زهرا",
    "شهلا",
    "حانيه",
    "ليلي",
    "عطيه",
    "جميله",
    "راحله",
    "مرجان",
    "يگانه",
    "مهلا",
    "ساجده",
    "آتنا",
    "صفيه",
    "منيره",
    "بهاره",
    "حليمه",
    "ميترا",
    "صغرا",
    "نگين",
    "نيلوفر",
    "ثنا",
    "نازنين",
    "كلثوم",
    "منيژه",
    "رباب",
    "نيره",
    "ياسمن",
    "آيدا",
    "زيبا",
    "شيرين",
    "الناز",
    "شهين",
    "وجيهه",
    "آذر",
    "انسيه",
    "رؤيا",
    "زكيه",
    "سپيده",
    "محيا",
    "نسترن",
    "كيميا",
    "محترم",
    "حبيبه",
    "فرخنده",
    "سيما",
    "فرحناز",
    "نيايش",
    "سودابه",
    "مهتاب",
    "ساناز",
    "صبا",
    "مهشيد",
    "رضيه",
    "سيده مريم",
    "عاليه",
    "نسيم",
    "صفورا",
    "بهناز",
    "حوريه",
    "شيما",
    "مژده",
    "وحيده",
    "رحيمه",
    "زهراالسادات",
    "شكوفه",
    "مريم السادات",
    "هما",
    "طوبي",
    "شيوا",
    "گوهر",
    "مريم سادات",
    "پري",
    "ستاره",
  ]

  firstNamesMale = @[
    "علی",
    "محمد",
    "مهدي",
    "حسين",
    "عليرضا",
    "محمدرضا",
    "رضا",
    "اميرحسين",
    "محمدحسين",
    "ابوالفضل",
    "حسن",
    "محسن",
    "محمدمهدي",
    "احمد",
    "عباس",
    "سعيد",
    "محمدعلي",
    "مرتضي",
    "مصطفي",
    "مجيد",
    "محمدجواد",
    "مجتبي",
    "محمود",
    "حميدرضا",
    "حميد",
    "جواد",
    "ابراهيم",
    "اميرمحمد",
    "محمدامين",
    "سجاد",
    "اميرعلي",
    "غلامرضا",
    "امير",
    "مسعود",
    "علي اكبر",
    "هادي",
    "اكبر",
    "محمدحسن",
    "علي اصغر",
    "احسان",
    "حامد",
    "سيدعلي",
    "اميررضا",
    "امين",
    "رسول",
    "سيدمحمد",
    "اسماعيل",
    "احمدرضا",
    "اصغر",
    "ميثم",
    "وحيد",
    "ميلاد",
    "داود",
    "سعيده",
    "ناصر",
    "روح اله",
    "علي رضا",
    "سيدحسين",
    "محمدصادق",
    "سهيلا",
    "محمدطاها",
    "قاسم",
    "سيدمهدي",
    "عرفان",
    "عزت",
    "صادق",
    "يوسف",
    "اميرمهدي",
    "اميرعباس",
    "ايمان",
    "جعفر",
    "منصور",
    "محمدصالح",
    "نصرت",
    "غلامحسين",
    "عبداله",
    "كاظم",
    "علي محمد",
    "حسينعلي",
    "سيدرضا",
    "مسلم",
    "دانيال",
    "عباسعلي",
    "محمدهادي",
    "حجت",
    "عبدالرضا",
    "محمدتقي",
    "مهرداد",
    "غلامعلي",
    "حبيب",
    "سيدمصطفي",
    "رحيم",
    "ياسين",
    "سيدمحمدرضا",
    "متين",
    "سيداحمد",
    "موسي",
    "ابوالقاسم",
    "بهروز",
    "جلال",
    "سبحان",
    "سيدحسن",
    "سيدمحسن",
    "فرهاد",
    "محمدباقر",
    "روح الله",
    "مهران",
    "حمزه",
    "پارسا",
    "سيدمحمدحسين",
    "طاها",
    "سينا",
    "حجت اله",
    "سيدعليرضا",
    "يونس",
    "بهنام",
    "حبيب اله",
    "ياسر",
    "محمدمتين",
    "پوريا",
    "سيدمحمدمهدي",
    "عادل",
    "كريم",
    "حيدر",
    "اسمعيل",
    "سيدمجتبي",
    "يداله",
    "سيداميرحسين",
    "رمضان",
    "صالح",
    "سيدعباس",
    "سيدمرتضي",
    "بهزاد",
    "جمال",
    "حسام",
    "سيدابوالفضل",
    "عيسي",
    "هاشم",
    "سيدجواد",
    "جليل",
    "عبدالحسين",
    "نادر",
    "فرزاد",
    "نيما",
    "قربانعلي",
    "مبين",
    "ايليا",
    "فردوس",
    "فيروزه",
    "بهرام",
    "حسنعلي",
    "سيدمحمود",
    "محمدياسين",
    "محمدعرفان",
    "محمدكاظم",
    "منوچهر",
    "معين",
    "بهمن",
    "ابوذر",
    "شهرام",
    "يعقوب",
    "پيمان",
    "داريوش",
  ]

  firstNames = firstNamesFemale & firstNamesMale

  lastNames = @[
    "آدینه",
    "آریان‌پور",
    "آژند",
    "آشتیانی",
    "آشنا",
    "آشوری",
    "آقاجری",
    "آهنگر",
    "آهنگری",
    "آهی",
    "آیتی",
    "ابتکار",
    "ابریشمی",
    "ابطحی",
    "ابوذر",
    "ادب",
    "ارسباران",
    "استادی",
    "اشتری",
    "اشراقی",
    "اشکوری",
    "اصفهانی",
    "اصلانی",
    "اعتبار",
    "اعتماد",
    "اعلم",
    "افخم",
    "افخمی",
    "اللهیاری",
    "الهام",
    "امانت",
    "امانی",
    "امیری",
    "امین‌زاده",
    "انتظامی",
    "انوار",
    "انوری",
    "انوشه",
    "اوستا",
    "ایمانی",
    "باستانی",
    "باطنی",
    "باغچه‌بان",
    "باهنر",
    "بحرینی",
    "بخاری",
    "بختیار",
    "بختیاری",
    "بدخشانی",
    "برزویی",
    "بزرگ‌نیا",
    "بهاور",
    "بهبهانی",
    "بهشتی",
    "بیگی",
    "پارسا",
    "پارسی",
    "پازارگاد",
    "پازوکی",
    "پایا",
    "بلوری",
    "پایدار",
    "پایور",
    "پستا",
    "پناهنده",
    "پناهی",
    "پناهیان",
    "پورناظری",
    "پ (ادامه)",
    "پورنگ",
    "پیران",
    "پیرحیاتی",
    "پیوندی",
    "تابش",
    "تبریزی",
    "ترکاشوند",
    "ترکان",
    "توسلی",
    "توفیق",
    "توفیقی",
    "توکل",
    "توکلیان",
    "تهرانی",
    "ثابتی",
    "جعفریان",
    "جمادی",
    "جنتی",
    "جهانبگلو",
    "جهانگیری",
    "جهانی",
    "چاوشی",
    "چگنی",
    "چلبی",
    "چنگیزی",
    "حائری",
    "حجتی",
    "حسابی",
    "حقانی",
    "حقیقی",
    "حکمت",
    "حکمی",
    "حکیمی",
    "حیاتی",
    "خاتمی",
    "خامنه‌ای",
    "خاموشی",
    "خداپناهی",
    "خدایی",
    "خراسانی",
    "خرم‌آبادی",
    "خسروپناه",
    "خمسه",
    "خوئینی",
    "خوئینی‌ها",
    "خیابانی",
    "داد",
    "دانایی‌فر",
    "دانایی‌فرد",
    "داودی",
    "داور",
    "دباغ",
    "درگاهی",
    "دری",
    "دستغیب",
    "دهقان",
    "دیباج",
    "ذاکری",
    "راسخ",
    "راوندی",
    "رجایی",
    "رحماندوست",
    "رحمانیان",
    "رستمی",
    "رسولی",
    "رفیعی",
    "رنجبر",
    "ر (ادامه)",
    "رنگرز",
    "روحانی",
    "روزبه",
    "رهنما",
    "زارع",
    "زالی",
    "زرشناس",
    "زمردیان",
    "زهرایی",
    "زین‌الدین",
    "ساعی",
    "سبحانی",
    "سبزواری",
    "سپه‌وند",
    "ستاری",
    "سحاب",
    "سحابی",
    "سراج",
    "سرشار",
    "سرمد",
    "سروستانی",
    "سروش",
    "سلامت",
    "سیف",
    "سیف‌زاده",
    "شادمهر",
    "شاملو",
    "شاه‌حسینی",
    "شاهی",
    "شبستری",
    "شجاعی",
    "شرع‌پسند",
    "شرف",
    "شریعتمداری",
    "شریعتی",
    "شریف",
    "شریفیان",
    "شفا",
    "شهیدی",
    "شیخ‌الاسلامی",
    "شیرازی",
    "شیرمحمدی",
    "شیروانی",
    "صانعی",
    "صباغ",
    "صدر",
    "صدیق",
    "صدیقی",
    "صغیری",
    "صفوی",
    "ضابطی",
    "طالب‌زاده",
    "طالقانی",
    "طباطبائی",
    "طبیب‌زاده",
    "طریقت",
    "ظریف",
    "عارف",
    "عاشوری",
    "عالی",
    "عبادی",
    "عبدالکریمی",
    "عبدالملکی",
    "عراقی",
    "عزیزی",
    "عصار",
    "عقیلی",
    "علم",
    "علم‌الهدی",
    "علی عسگری",
    "علی‌آبادی",
    "علیا",
    "علی‌پور",
    "علی‌زمانی",
    "عنایت",
    "غضنفری",
    "غنی",
    "فارسی",
    "فاطمی",
    "فانی",
    "فتاحی",
    "فرامرزی",
    "فرج",
    "فرشیدورد",
    "فرمانفرمائیان",
    "فروتن",
    "فرهنگ",
    "فریاد",
    "فنایی",
    "فنی‌زاده",
    "فولادوند",
    "فهمیده",
    "قاضی",
    "قانعی",
    "قانونی",
    "قمیشی",
    "قنبری",
    "قهرمان",
    "قهرمانی",
    "قهرمانیان",
    "قهستانی",
    "کاکاوند",
    "کامکار",
    "کاملی",
    "کاویانی",
    "کدیور",
    "کردبچه",
    "کرمانی",
    "کریمی",
    "کلباسی",
    "کمالی",
    "کاشانی",
    "کوشکی",
    "کهنمویی",
    "کیان",
    "کیانی",
    "گل محمدی",
    "گلپایگانی",
    "گنجی",
    "لاجوردی",
    "لاچینی",
    "لاهوتی",
    "لنکرانی",
    "لوکس",
    "مجاهد",
    "مجتبایی",
    "مجتبوی",
    "مجتهد شبستری",
    "مجتهدی",
    "مجرد",
    "محجوب",
    "محجوبی",
    "محدثی",
    "محمدرضایی",
    "محمدی",
    "مددی",
    "مرادخانی",
    "مرتضوی",
    "مستوفی",
    "مشا",
    "مصاحب",
    "مصباح",
    "مصباح‌زاده",
    "مطهری",
    "مظفر",
    "معارف",
    "معروف",
    "معین",
    "مفتاح",
    "مقدم",
    "ملایری",
    "ملک",
    "ملکیان",
    "منوچهری",
    "موحد",
    "م (ادامه)",
    "موسوی",
    "موسویان",
    "مهاجرانی",
    "مهدی‌پور",
    "میرباقری",
    "میرزاده",
    "میرسپاسی",
    "میزبانی",
    "ناظری",
    "نامور",
    "نجفی",
    "ندوشن",
    "نراقی",
    "نعمت‌زاده",
    "نقدی",
    "نقیب‌زاده",
    "نواب",
    "نوبخت",
    "نوبختی",
    "نهاوندی",
    "نیشابوری",
    "واثقی",
    "واعظ",
    "واعظ‌زاده",
    "واعظی",
    "وکیلی",
    "هاشمی",
    "هاشمی رفسنجانی",
    "هاشمیان",
    "هامون",
    "هدایت",
    "هراتی",
    "هروی",
    "همایون",
    "همت",
    "همدانی",
    "هوشیار",
    "هومن",
    "یاحقی",
    "یادگار",
    "یثربی",
    "یلدا",
    "ضرغامی",
  ]

  prefixesFemale = @[
    "خانم",
    "سرکار خانم",
  ]
  prefixesMale = @[
    "آقای",
    "جناب آقای",
  ]
  prefixes = prefixesFemale & prefixesMale

  suffixesFemale = @[""]
  suffixesMale = @[""]
  suffixes = suffixesFemale & suffixesMale

proc format(f: Faker, fmt: string): string =
  let
    firstNameFemale = f.rand.sample(firstNamesFemale)
    firstNameMale = f.rand.sample(firstNamesMale)
    lastName = f.rand.sample(lastNames)
    prefixFemale = f.rand.sample(prefixesFemale)
    prefixMale = f.rand.sample(prefixesMale)
  fmt % @[
    "firstNameFemale", firstNameFemale,
    "firstNameMale", firstNameMale,
    "lastName", lastName,
    "prefixFemale", prefixFemale,
    "prefixMale", prefixMale,
    ]

genSampleProc fa_IR, [
    (firstName, firstNames, "یک اسم به تصادف انتخاب میکند"),
    (firstNameFemale, firstNamesFemale, "یک اسم دختر تصادفی"),
    (firstNameMale, firstNamesMale, "یک اسم پسر تصادفی"),
    (lastName, lastNames, "یک نام خانوادگی تصادفی"),
    (lastNameFemale, lastNames, "یک نام خاوادگی تصادفی دخترانه؟؟"),
    (lastNameMale, lastNames, "یک نام خانوادگی تصادفی پسرانه؟؟"),
    (prefix, prefixes, "یک پیشوند نام"),
    (prefixFemale, prefixesFemale, "یک پیشوند نام زنانه"),
    (prefixMale, prefixesMale, "یک پیشوند نام مردانه"),
    (suffix, suffixes, "پسوند نام :: موجود نیست"),
    (suffixFemale, suffixesFemale, "پسوند نام زنانه :: موجود نیست"),
    (suffixMale, suffixesMale, "پسوند نام مردانه :: موجود نیست"),
  ]

genSampleFormatProc fa_IR, [
    (nameFemale, formatsFemale, "یک نام زنانه به طور کامل"),
    (nameMale, formatsMale, "یک نام مردانه به طور کامل"),
    (name, formats, "یک نام به طور کامل"),
  ]
