import util, ../base, address/[en_US, ja_JP]
export base

genProc [
  address,
  buildingNumber,
  city,
  cityPrefix,
  citySuffix,
  country,
  #countryCode,
  militaryApo,
  militaryDpo,
  militaryShip,
  militaryState,
  postalcode,
  #postalcodeInState,
  postalcodePlus4,
  postcode,
  secondaryAddress,
  state,
  #stateAbbr,
  streetAddress,
  streetName,
  streetSuffix,
  zipcode,
  #zipcodeInState,
  zipcodePlus4,
  ],
  [en_US, ja_JP]
