# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import bank/[bank_en_US]
export base

genProc bank,
  [
    bankCountry,
    bban,
    iban,
  ], [
    en_US,
  ]