# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import company/[company_en_US, company_ja_JP]
export base

genProc company,
  [
    bs,
    catchPhrase,
    company,
    companySuffix,
  ], [
    en_US,
    ja_JP,
  ]