# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import currency/[currency_en_US]
export base

genProc currency,
  [
    currency,
    currencyCode,
    currencyName,
    currencySymbol,
    cryptocurrency,
    cryptocurrencyCode,
    cryptocurrencyName,
  ], [
    en_US,
  ]