# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import job/[job_en_US, job_ja_JP]
export base

genProc job,
  [
    job,
  ], [
    en_US,
    ja_JP,
  ]