# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import ../base
import lorem/[lorem_en_US, lorem_ja_JP]
export base

proc word*(f: Faker): string =
  ## Generates random word.
  runnableExamples:
    let f = newFaker()
    echo f.word()

  case f.locale
  of "en_US": lorem_en_US.word(f)
  of "ja_JP": lorem_ja_JP.word(f)
  else: lorem_en_US.word(f)
