# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import person/[person_en_US, person_ja_JP]
export base

genProc person,
  [
    firstName,
    firstNameFemale,
    firstNameMale,
    lastName,
    lastNameFemale,
    lastNameMale,
    name,
    nameFemale,
    nameMale,
    prefix,
    prefixFemale,
    prefixMale,
    suffix,
    suffixFemale,
    suffixMale,
  ], [
    en_US,
    ja_JP,
  ]