# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import phone_number/[phone_number_en_US, phone_number_ja_JP]
export base

genProc phone_number,
  [
    phoneNumber,
    msisdn,
  ], [
    en_US,
    ja_JP,
  ]