# ----------------------------------------------- #
# This module was generated by 'generator' tool . #
# See 'tools/generator'.                          #
# ----------------------------------------------- #

import ../base
import ssn/ssn_en_US
export base

proc ssn*(f: Faker): string =
  ## Generates random job.
  runnableExamples:
    let f = newFaker()
    echo f.ssn()

  case f.locale
  of "en_US": ssn_en_US.ssn(f)
  else: ssn_en_US.ssn(f)
