# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import util
import ../base
import user_agent/[user_agent_en_US]
export base

genProc user_agent,
  [
    userAgent,
    chrome,
    firefox,
    opera,
    safari,
    internetExplorer,
    linuxPlatformToken,
    macPlatformToken,
    androidPlatformToken,
    iosPlatformToken,
    windowsPlatformToken,
    linuxProcessor,
    macProcessor,
  ], [
    en_US,
  ]