# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import ../base
import word/[word_ja_JP, word_en_US]
export base

proc word*(f: Faker): string =
  ## Generates random word.
  runnableExamples:
    let f = newFaker()
    echo f.word()

  case f.locale
  of "ja_JP": word_ja_JP.word(f)
  of "en_US": word_en_US.word(f)
  else: word_en_US.word(f)
