# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import provider/[address, automotive, bank, company, currency, file, isbn, job, lorem, person, phone_number, user_agent]
export address, automotive, bank, company, currency, file, isbn, job, lorem, person, phone_number, user_agent