# ----------------------------------------------- #
# This module was generated by 'nimble genProvs'. #
# See 'faker.nimble'.                             #
# ----------------------------------------------- #

import provider/[address, bank, company, job, person, phone_number, user_agent]
export address, bank, company, job, person, phone_number, user_agent